### ISSUE TITLE
Apache Tomcat 8.5.11 - Virtual Machine - Probe 3.2.0 which downloaded at 2019

### ISSUE THREAD

**Issue by beatic** [psi-probe/psi-probe#1351]
Hi,
first of all, let me give the information that may useful:

```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

```
$ ./version.sh
Using CATALINA_BASE:   /opt/BACKEND
Using CATALINA_HOME:   /opt/BACKEND
Using CATALINA_TMPDIR: /opt/BACKEND/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /opt/BACKEND/bin/bootstrap.jar:/opt/BACKEND/bin/tomcat-juli.jar
Server version: Apache Tomcat/8.5.11
Server built:   Jan 10 2017 21:02:52 UTC
Server number:  8.5.11.0
OS Name:        Linux
OS Version:     2.6.32-696.el6.x86_64
Architecture:   amd64
JVM Version:    1.8.0_151-b12
JVM Vendor:     Oracle Corporation
```

```
export CATALINA_OPTS="$CATALINA_OPTS -Xms1024M"
export CATALINA_OPTS="$CATALINA_OPTS -Xmx8192M"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote.host=ip_address"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote.ssl=false"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote.local.only=false"
export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote.rmi.port=false"
```

  <role rolename="manager-gui"/>
  <role rolename="manager-script"/>
  <role rolename="admin-gui"/> 
  <role rolename="probeuser"/>
  <role rolename="poweruser"/>
  <role rolename="poweruserplus"/>
			
  <user username="tomcat" password="tomcat_password" roles="manager-gui"/>
</tomcat-users>

Please help to check below error from probe.log:
[error_probe.txt](https://github.com/psi-probe/psi-probe/files/3339642/error_probe.txt)

We have several webapps running besides Probe. 
After installed Probe, the webapps still running fine. 
After authentication dialog shows up, I inputted the username and password. 
Then this message shows up:

> There was an error
> 
> Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible!

I have reviewed the issues #1127, and I have searched for javax.mail using this command but there is no any result.

`find / -name javax.mail`

I also have reviewed the issue #1073, is that owner of the folder may be the root cause?
Currently, the "work" folder is owned by "beatic" and "probe" folder (inside folder "webapps") is owned by "root".

Let me know if you need any more info of explanation.
Thank you.

**Comment by hazendaz** [comment]
Can you give psi probe 3.3.0 a try?  The issues with stats was fixed in that release.  I do not believe that is your ultimate issue but it will clear the errors listed in your current log.

**Comment by beatic** [comment]
Hi @hazendaz, 
thank you for your suggestion. 
Sure, I will try using PSI Probe 3.3.0.
From Github Releases, it gives me this URL (https://github.com/psi-probe/psi-probe/releases/download/3.2.0/probe.war).
So, I will try to get the latest from Maven Central.
Here I attached the screenshot which shows which file that I downloaded (please refer to the highlighted one).
![Anotasi 2019-07-01 011703](https://user-images.githubusercontent.com/42235450/60400486-7dd8a980-9b9e-11e9-9a4d-5f21c80bc48d.jpg)

Please correct me if I wrong. 
Thank you.

**Comment by hazendaz** [comment]
Yes that is correct.  I'll update the one as well in github.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by beatic** [comment]
Hi @hazendaz ,
Thank you for your confirmation.
After tried to install PSI PROBE 3.3.0, I still get the same error which is:

> There was an error
> 
> Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible!

Here I attached the probe.log:
[log_probe_3_3_0.log](https://github.com/psi-probe/psi-probe/files/3343769/log_probe_3_3_0.log)

Please let me know if you need any more info of explanation.
Thank you.

**Comment by beatic** [comment]
Hi @hazendaz , 
I would like to inform you that the PSI PROBE 3.3.0 is working fine on our virtual machine. 
FYI, we have 2 VM, let's say VM 1 and VM 2. 
On VM 1, I need to change the owner and permissions from "beatic" to "root".
Meanwhile on VM 2, without any changes, the PSI PROBE 3.3.0 working fine. 
The point is, thank you for this discussion.
We are really appreciate it.
Cheers.
