### ISSUE TITLE
Job threw an unhandled exception

### ISSUE THREAD

**Issue by 1506085843** [psi-probe/psi-probe#2201]
![image](https://user-images.githubusercontent.com/39946319/183791655-5dc23833-a31b-4458-a154-db1d43cac614.png)

The tomcat version I am using is 9.0.58.0 and I am getting an error, the log is as follows:

> 09:30:30.000 ERROR {Probe_Quartz-2} [org.quartz.core.ErrorLogger] Job (DEFAULT.connectorStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at psiprobe.beans.ContainerListenerBean.initialize(ContainerListenerBean.java:150)
	at psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:294)
	at psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean.collect(ConnectorStatsCollectorBean.java:50)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 common frames omitted

**Comment by hazendaz** [comment]
What version of Psi probe are you using?  I feel like that was fixed already.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: xiaohaitang ***@***.***>
Sent: Tuesday, August 9, 2022 9:44:48 PM
To: psi-probe/psi-probe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [psi-probe/psi-probe] Job threw an unhandled exception (Issue #2201)


[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F39946319%2F183791655-5dc23833-a31b-4458-a154-db1d43cac614.png&data=05%7C01%7C%7C04a7437f19ea41dd4b8c08da7a71e90e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637956926895125516%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WN55hAG6D68c%2Fv2ZCmccCt7QmaAxuXwEPiH9PIxbHb4%3D&reserved=0>

The tomcat version I am using is 9.0.58.0 and I am getting an error, the log is as follows:

09:30:30.000 ERROR {Probe_Quartz-2} [org.quartz.core.ErrorLogger] Job (DEFAULT.connectorStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean] failed; nested exception is java.lang.NullPointerException
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
at psiprobe.beans.ContainerListenerBean.initialize(ContainerListenerBean.java:150)
at psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:294)
at psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean.collect(ConnectorStatsCollectorBean.java:50)
at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
... 3 common frames omitted

**Comment by 1506085843** [comment]
@hazendaz The Psi probe I'm using is 3.5.8 Release, I don't think the issue has been fixed, I've found other people have raised issues

**Comment by hazendaz** [comment]
Please try the latest, I'm pretty sure this was fixed a while ago.  Latest is 3.6.0.

**Comment by earlraneses** [comment]
@hazendaz, I am also encountering this on the latest snapshot build [psi-probe-web-3.6.1-20221117.023452-70.war] from sonatype

> 15:46:31.265 ERROR {Probe_Quartz-2} [org.quartz.core.ErrorLogger] Job (DEFAULT.connectorStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean] failed; nested exception is java.lang.NullPointerException
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
        at psiprobe.beans.ContainerListenerBean.initialize(ContainerListenerBean.java:150)
        at psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:294)
        at psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean.collect(ConnectorStatsCollectorBean.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
        ... 3 common frames omitted

**Comment by earlraneses** [comment]
@1506085843, were you able to find the root cause for your issue and how you fixed it?

**Comment by 1506085843** [comment]
> @1506085843, were you able to find the root cause for your issue and how you fixed it?

The latest version doesn't fix this issue, try with previous few versions

**Comment by hazendaz** [comment]
I need more details as to specific setup.  Every time this is reported, I try it and everything is fine.  I tested latest master tonight using tomcat 9.0.52 (old one) on jdk 17.0.5, no issues.  Had it running with a copy of jenkins.war and displaytag.war.  No issues.  Maybe it a timing issue? Is this not seen when app starts?  How long should I leave it running?  Those items might help resolve whatever the issue is.

**Comment by earlraneses** [comment]
@hazendaz, it may be an intermittent error. I tried recent snapshot from sonatype (psi-probe-web-3.6.1-20221117.145930-72.war) and I am not seeing the error now. I'll observe and try to find a pattern.

**Comment by hazendaz** [comment]
closing as no further info on the condition.  if seen again, feel free to open again with additional information.
